### ISSUE TITLE
got an pip install timm error. reinstalled both timm and Miaoshouai Tagger multiple times

### ISSUE THREAD

**Issue by NaikKarthik10** [miaoshouai/ComfyUI-Miaoshouai-Tagger#16]
# ComfyUI Error Report
## Error Details
- **Node Type:** Miaoshouai_Tagger
- **Exception Type:** ImportError
- **Exception Message:** This modeling file requires the following packages that were not found in your environment: timm. Run `pip install timm`
## Stack Trace
```
  File "C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Miaoshouai-Tagger\nodes.py", line 136, in start_tag
    model = AutoModelForCausalLM.from_pretrained(model_path, attn_implementation=attention, device_map=device,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\models\auto\auto_factory.py", line 551, in from_pretrained
    model_class = get_class_from_dynamic_module(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\dynamic_module_utils.py", line 502, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
                   ^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\dynamic_module_utils.py", line 327, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\dynamic_module_utils.py", line 182, in check_imports
    raise ImportError(

```
## System Information
- **ComfyUI Version:** v0.2.2
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce GTX 1650 : native
  - **Type:** cuda
  - **VRAM Total:** 4294639616
  - **VRAM Free:** 3458675508
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2024-09-16 21:27:08,043 - root - INFO - Total VRAM 4096 MB, total RAM 7598 MB
2024-09-16 21:27:08,044 - root - INFO - pytorch version: 2.4.1+cu124
2024-09-16 21:27:08,046 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-16 21:27:08,046 - root - INFO - Device: cuda:0 NVIDIA GeForce GTX 1650 : native
2024-09-16 21:27:09,391 - root - INFO - Using pytorch cross attention
2024-09-16 21:27:10,842 - root - INFO - [Prompt Server] web root: C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\web
2024-09-16 21:27:11,411 - root - WARNING - Traceback (most recent call last):
  File "C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Karthik\\OneDrive\\文档\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI\\__init__.py'

2024-09-16 21:27:11,411 - root - WARNING - Cannot import C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI module for custom nodes: [Errno 2] No such file or directory: 'C:\\Users\\Karthik\\OneDrive\\文档\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI\\__init__.py'
2024-09-16 21:27:11,884 - root - WARNING - Skip C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger module for custom nodes due to the lack of NODE_CLASS_MAPPINGS.
2024-09-16 21:27:11,898 - root - WARNING - Traceback (most recent call last):
  File "C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_tagger\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_tagger\nodes.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'

2024-09-16 21:27:11,898 - root - WARNING - Cannot import C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_tagger module for custom nodes: No module named 'matplotlib'
2024-09-16 21:27:11,916 - root - INFO - 
Import times for custom nodes:
2024-09-16 21:27:11,916 - root - INFO -    0.0 seconds: C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-09-16 21:27:11,916 - root - INFO -    0.0 seconds: C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\custom_nodes\Lora-Training-in-Comfy
2024-09-16 21:27:11,916 - root - INFO -    0.0 seconds: C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\custom_nodes\Image-Captioning-in-ComfyUI
2024-09-16 21:27:11,916 - root - INFO -    0.0 seconds (IMPORT FAILED): C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI
2024-09-16 21:27:11,918 - root - INFO -    0.0 seconds (IMPORT FAILED): C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
2024-09-16 21:27:11,918 - root - INFO -    0.0 seconds: C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-09-16 21:27:11,918 - root - INFO -    0.0 seconds: C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_tag_fillter
2024-09-16 21:27:11,918 - root - INFO -    0.0 seconds (IMPORT FAILED): C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_tagger
2024-09-16 21:27:11,918 - root - INFO -    0.0 seconds: C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Miaoshouai-Tagger
2024-09-16 21:27:11,918 - root - INFO -    0.4 seconds: C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-09-16 21:27:11,919 - root - INFO - 
2024-09-16 21:27:11,927 - root - INFO - Starting server

2024-09-16 21:27:11,928 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-09-16 21:27:34,044 - root - INFO - got prompt
2024-09-16 21:27:37,455 - root - ERROR - !!! Exception during processing !!! This modeling file requires the following packages that were not found in your environment: timm. Run `pip install timm`
2024-09-16 21:27:37,457 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Miaoshouai-Tagger\nodes.py", line 136, in start_tag
    model = AutoModelForCausalLM.from_pretrained(model_path, attn_implementation=attention, device_map=device,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\models\auto\auto_factory.py", line 551, in from_pretrained
    model_class = get_class_from_dynamic_module(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\dynamic_module_utils.py", line 502, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\dynamic_module_utils.py", line 327, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\dynamic_module_utils.py", line 182, in check_imports
    raise ImportError(
ImportError: This modeling file requires the following packages that were not found in your environment: timm. Run `pip install timm`

2024-09-16 21:27:37,461 - root - INFO - Prompt executed in 3.26 seconds
2024-09-16 21:37:05,349 - root - INFO - got prompt
2024-09-16 21:37:08,878 - root - ERROR - !!! Exception during processing !!! This modeling file requires the following packages that were not found in your environment: timm. Run `pip install timm`
2024-09-16 21:37:08,883 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Miaoshouai-Tagger\nodes.py", line 136, in start_tag
    model = AutoModelForCausalLM.from_pretrained(model_path, attn_implementation=attention, device_map=device,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\models\auto\auto_factory.py", line 551, in from_pretrained
    model_class = get_class_from_dynamic_module(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\dynamic_module_utils.py", line 502, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\dynamic_module_utils.py", line 327, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Karthik\OneDrive\文档\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\dynamic_module_utils.py", line 182, in check_imports
    raise ImportError(
ImportError: This modeling file requires the following packages that were not found in your environment: timm. Run `pip install timm`

2024-09-16 21:37:08,886 - root - INFO - Prompt executed in 3.37 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":15,"last_link_id":8,"nodes":[{"id":8,"type":"Tensorboard Access","pos":{"0":155,"1":722},"size":{"0":210,"1":26},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[],"properties":{"Node name for S&R":"Tensorboard Access"}},{"id":9,"type":"ShowText|pysssss","pos":{"0":612,"1":392},"size":{"0":315,"1":76},"flags":{},"order":3,"mode":0,"inputs":[{"name":"text","type":"STRING","link":2,"widget":{"name":"text"}}],"outputs":[{"name":"STRING","type":"STRING","links":[3],"slot_index":0,"shape":6}],"properties":{"Node name for S&R":"ShowText|pysssss"},"widgets_values":["","0bb01-16424436968521.png\n5f93c527db140f96e0c75be33801a00d.png\nNezuko_Advanced_Form_visual_Hinokami_Chronicles.png\nNezuko_anime_design.png\nNezuko_as_a_child.png\nNezuko_colored_body.png\nNezuko_conquers_the_sun.png\nNezuko_human_appearance.png\nNezuko_welcomes_Zenitsu_back.png\nt58477dmluc61.png"]},{"id":6,"type":"LoRA Caption Save","pos":{"0":1170,"1":404},"size":{"0":315,"1":130},"flags":{},"order":6,"mode":0,"inputs":[{"name":"namelist","type":"STRING","link":3,"widget":{"name":"namelist"}},{"name":"path","type":"STRING","link":1,"widget":{"name":"path"}},{"name":"text","type":"STRING","link":8,"widget":{"name":"text"}}],"outputs":[],"properties":{"Node name for S&R":"LoRA Caption Save"},"widgets_values":["","",""," "]},{"id":15,"type":"PreviewImage","pos":{"0":1261,"1":608},"size":{"0":210,"1":26},"flags":{},"order":5,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":7}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"}},{"id":14,"type":"Miaoshouai_Tagger","pos":{"0":681,"1":622},"size":{"0":400,"1":400},"flags":{},"order":4,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":4},{"name":"filenames","type":"STRING","link":5,"widget":{"name":"filenames"}},{"name":"captions","type":"STRING","link":6,"widget":{"name":"captions"}}],"outputs":[{"name":"images","type":"IMAGE","links":[7],"slot_index":0,"shape":6},{"name":"filenames","type":"STRING","links":null,"slot_index":1,"shape":6},{"name":"captions","type":"STRING","links":[8],"slot_index":2,"shape":6},{"name":"folder_path","type":"STRING","links":null,"shape":3},{"name":"batch_size","type":"INT","links":null,"shape":3}],"properties":{"Node name for S&R":"Miaoshouai_Tagger"},"widgets_values":["promptgen_base_v1.5","C:\\Users\\Karthik\\Downloads\\1_NezukoLora","mixed",1024,4,"never","","","","","replace_tags eg:search1:replace1;search2:replace2"]},{"id":2,"type":"Lora Training in Comfy (Advanced)","pos":{"0":50,"1":80},"size":{"0":315,"1":562},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[],"properties":{"Node name for S&R":"Lora Training in Comfy (Advanced)"},"widgets_values":["dreamshaper_8.safetensors","No","networks.lora",32,32,512,"C:\\Users\\Karthik\\Downloads\\1_NezukoLora",1,10,10,0,0,0.0001,0.0001,"cosine_with_restarts",1,"AdamW8bit","Desired name for LoRA.","lora",0,2,"models/loras"]},{"id":7,"type":"LoRA Caption Load","pos":{"0":50,"1":829},"size":{"0":315,"1":98},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"Name list","type":"STRING","links":[2,5],"slot_index":0,"shape":3},{"name":"path","type":"STRING","links":[1,6],"slot_index":1,"shape":3},{"name":"Image list","type":"IMAGE","links":[4],"slot_index":2,"shape":3}],"properties":{"Node name for S&R":"LoRA Caption Load"},"widgets_values":["C:\\Users\\Karthik\\Downloads\\1_NezukoLora"]}],"links":[[1,7,1,6,1,"STRING"],[2,7,0,9,0,"STRING"],[3,9,0,6,0,"STRING"],[4,7,2,14,0,"IMAGE"],[5,7,0,14,1,"STRING"],[6,7,1,14,2,"STRING"],[7,14,0,15,0,"IMAGE"],[8,14,2,6,2,"STRING"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.7513148009015777,"offset":[50.58196311659935,-51.33183161819004]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by Latentnaut** [comment]
it's happening to me, on a totally fresh new Comfy installation.

```
Error occurred when executing Miaoshouai_Tagger:

No module named 'timm'

File "C:\AI\ComfyUI_windows_portable_new\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\AI\ComfyUI_windows_portable_new\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\AI\ComfyUI_windows_portable_new\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\AI\ComfyUI_windows_portable_new\ComfyUI\custom_nodes\ComfyUI-Miaoshouai-Tagger\nodes.py", line 151, in start_tag
from florence2_base_ft.modeling_florence2 import Florence2ForConditionalGeneration
File "C:\AI\ComfyUI_windows_portable_new\ComfyUI\models\LLM\Florence-2-base-PromptGen-v1.5\florence2_base_ft\modeling_florence2.py", line 29, in
from timm.models.layers import DropPath, trunc_normal_
```

**Comment by miaoshouai** [comment]
python_embeded\python.exe -m pip install timm
you may also need to do that for accelerate
