### ISSUE TITLE
ModuleNotFoundError: No module named 'florence2_base_ft'

### ISSUE THREAD

**Issue by Jacob-HYG** [miaoshouai/ComfyUI-Miaoshouai-Tagger#18]
# ComfyUI Error Report
## Error Details
- **Node Type:** Miaoshouai_Tagger
- **Exception Type:** ModuleNotFoundError
- **Exception Message:** No module named 'florence2_base_ft'
## Stack Trace
```
  File "F:\ComfyUI-aki-v1.4\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "F:\ComfyUI-aki-v1.4\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "F:\ComfyUI-aki-v1.4\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "F:\ComfyUI-aki-v1.4\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Miaoshouai-Tagger\nodes.py", line 138, in start_tag
    from florence2_base_ft.modeling_florence2 import Florence2ForConditionalGeneration

```
## System Information
- **ComfyUI Version:** v0.2.2-80-g8733191
- **Arguments:** F:\ComfyUI-aki-v1.4\main.py --auto-launch --preview-method none --disable-cuda-malloc
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.4.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 12884377600
  - **VRAM Free:** 10833044832
  - **Torch VRAM Total:** 973078528
  - **Torch VRAM Free:** 54732128

## Logs
```
2024-09-28 12:17:40,220 - root - INFO - Total VRAM 12288 MB, total RAM 48965 MB
2024-09-28 12:17:40,220 - root - INFO - pytorch version: 2.4.1+cu124
2024-09-28 12:17:41,219 - root - INFO - xformers version: 0.0.28.post1
2024-09-28 12:17:41,220 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-28 12:17:41,220 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
2024-09-28 12:17:41,336 - root - INFO - Using xformers cross attention
2024-09-28 12:17:41,961 - root - INFO - [Prompt Server] web root: F:\ComfyUI-aki-v1.4\web
2024-09-28 12:17:43,345 - root - WARNING - Traceback (most recent call last):
  File "F:\ComfyUI-aki-v1.4\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\ComfyUI-aki-v1.4\\custom_nodes\\ComfyUI-Florence2\\__init__.py'

2024-09-28 12:17:43,345 - root - WARNING - Cannot import F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Florence2 module for custom nodes: [Errno 2] No such file or directory: 'F:\\ComfyUI-aki-v1.4\\custom_nodes\\ComfyUI-Florence2\\__init__.py'
2024-09-28 12:17:43,378 - root - INFO - Total VRAM 12288 MB, total RAM 48965 MB
2024-09-28 12:17:43,378 - root - INFO - pytorch version: 2.4.1+cu124
2024-09-28 12:17:43,378 - root - INFO - xformers version: 0.0.28.post1
2024-09-28 12:17:43,378 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-28 12:17:43,378 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
2024-09-28 12:17:48,632 - root - INFO - 
Import times for custom nodes:
2024-09-28 12:17:48,633 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\websocket_image_save.py
2024-09-28 12:17:48,633 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\AIGODLIKE-ComfyUI-Translation
2024-09-28 12:17:48,633 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\style_aligned_comfy
2024-09-28 12:17:48,633 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\sdxl_prompt_styler
2024-09-28 12:17:48,633 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ControlNet-LLLite-ComfyUI
2024-09-28 12:17:48,633 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\stability-ComfyUI-nodes
2024-09-28 12:17:48,633 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-TCD
2024-09-28 12:17:48,633 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\FreeU_Advanced
2024-09-28 12:17:48,633 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-FluxExt-MZ
2024-09-28 12:17:48,633 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\florence_dw
2024-09-28 12:17:48,633 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_densediffusion
2024-09-28 12:17:48,633 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-enricos-nodes
2024-09-28 12:17:48,633 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_TiledKSampler
2024-09-28 12:17:48,633 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_CatVTON_Wrapper
2024-09-28 12:17:48,633 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\wlsh_nodes
2024-09-28 12:17:48,633 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_IPAdapter_plus
2024-09-28 12:17:48,633 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\PowerNoiseSuite
2024-09-28 12:17:48,633 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\images-grid-comfy-plugin
2024-09-28 12:17:48,633 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-layerdiffuse
2024-09-28 12:17:48,633 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-PromptSelector
2024-09-28 12:17:48,633 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\steerable-motion
2024-09-28 12:17:48,633 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Custom-Scripts
2024-09-28 12:17:48,633 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_essentials
2024-09-28 12:17:48,633 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Miaoshouai-Tagger
2024-09-28 12:17:48,633 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_UltimateSDUpscale
2024-09-28 12:17:48,633 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Frame-Interpolation
2024-09-28 12:17:48,633 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\Derfuu_ComfyUI_ModdedNodes
2024-09-28 12:17:48,633 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-KJNodes
2024-09-28 12:17:48,633 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Advanced-ControlNet
2024-09-28 12:17:48,633 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\rgthree-comfy
2024-09-28 12:17:48,633 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Marigold
2024-09-28 12:17:48,634 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-GGUF
2024-09-28 12:17:48,634 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-IC-Light
2024-09-28 12:17:48,634 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\x-flux-comfyui
2024-09-28 12:17:48,634 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_NYJY
2024-09-28 12:17:48,634 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Kolors-MZ
2024-09-28 12:17:48,634 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-09-28 12:17:48,634 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\HivisionIDPhotos-ComfyUI
2024-09-28 12:17:48,634 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\comfyui_controlnet_aux
2024-09-28 12:17:48,634 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_smZNodes
2024-09-28 12:17:48,634 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-DynamiCrafterWrapper
2024-09-28 12:17:48,634 - root - INFO -    0.0 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Inspire-Pack
2024-09-28 12:17:48,634 - root - INFO -    0.1 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Crystools
2024-09-28 12:17:48,634 - root - INFO -    0.1 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-VideoHelperSuite
2024-09-28 12:17:48,634 - root - INFO -    0.1 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Long-CLIP
2024-09-28 12:17:48,634 - root - INFO -    0.2 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_InstantID
2024-09-28 12:17:48,634 - root - INFO -    0.2 seconds (IMPORT FAILED): F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Florence2
2024-09-28 12:17:48,634 - root - INFO -    0.3 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_FizzNodes
2024-09-28 12:17:48,634 - root - INFO -    0.3 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-CogVideoXWrapper
2024-09-28 12:17:48,634 - root - INFO -    0.3 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Easy-Use
2024-09-28 12:17:48,634 - root - INFO -    0.3 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Manager
2024-09-28 12:17:48,634 - root - INFO -    0.6 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_LayerStyle
2024-09-28 12:17:48,634 - root - INFO -    0.8 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Impact-Pack
2024-09-28 12:17:48,634 - root - INFO -    2.6 seconds: F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
2024-09-28 12:17:48,634 - root - INFO - 
2024-09-28 12:17:48,647 - root - INFO - Starting server

2024-09-28 12:17:48,647 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-09-28 12:18:08,037 - root - INFO - got prompt
2024-09-28 12:18:08,136 - root - ERROR - Failed to validate prompt for output 490:
2024-09-28 12:18:08,136 - root - ERROR - * (prompt):
2024-09-28 12:18:08,137 - root - ERROR -   - Required input is missing: images
2024-09-28 12:18:08,137 - root - ERROR - * Image Save with Prompt/Info (WLSH) 490:
2024-09-28 12:18:08,137 - root - ERROR -   - Required input is missing: images
2024-09-28 12:18:08,137 - root - ERROR - Output will be ignored
2024-09-28 12:18:08,222 - root - WARNING - WARNING: '519'
2024-09-28 12:18:12,599 - root - ERROR - !!! Exception during processing !!! No module named 'florence2_base_ft'
2024-09-28 12:18:12,600 - root - ERROR - Traceback (most recent call last):
  File "F:\ComfyUI-aki-v1.4\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\ComfyUI-aki-v1.4\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\ComfyUI-aki-v1.4\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI-aki-v1.4\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Miaoshouai-Tagger\nodes.py", line 138, in start_tag
    from florence2_base_ft.modeling_florence2 import Florence2ForConditionalGeneration
ModuleNotFoundError: No module named 'florence2_base_ft'

2024-09-28 12:18:12,601 - root - INFO - Prompt executed in 4.46 seconds
2024-09-28 12:18:19,935 - root - INFO - got prompt
2024-09-28 12:18:20,047 - root - ERROR - Failed to validate prompt for output 490:
2024-09-28 12:18:20,048 - root - ERROR - * (prompt):
2024-09-28 12:18:20,048 - root - ERROR -   - Required input is missing: images
2024-09-28 12:18:20,048 - root - ERROR - * Image Save with Prompt/Info (WLSH) 490:
2024-09-28 12:18:20,048 - root - ERROR -   - Required input is missing: images
2024-09-28 12:18:20,048 - root - ERROR - Output will be ignored
2024-09-28 12:18:20,124 - root - WARNING - WARNING: '519'
2024-09-28 12:18:20,496 - root - ERROR - !!! Exception during processing !!! No module named 'florence2_base_ft'
2024-09-28 12:18:20,496 - root - ERROR - Traceback (most recent call last):
  File "F:\ComfyUI-aki-v1.4\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\ComfyUI-aki-v1.4\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\ComfyUI-aki-v1.4\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI-aki-v1.4\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Miaoshouai-Tagger\nodes.py", line 138, in start_tag
    from florence2_base_ft.modeling_florence2 import Florence2ForConditionalGeneration
ModuleNotFoundError: No module named 'florence2_base_ft'

2024-09-28 12:18:20,497 - root - INFO - Prompt executed in 0.44 seconds
2024-09-28 12:18:24,119 - root - INFO - got prompt
2024-09-28 12:18:24,234 - root - ERROR - Failed to validate prompt for output 490:
2024-09-28 12:18:24,234 - root - ERROR - * (prompt):
2024-09-28 12:18:24,234 - root - ERROR -   - Required input is missing: images
2024-09-28 12:18:24,235 - root - ERROR - * Image Save with Prompt/Info (WLSH) 490:
2024-09-28 12:18:24,235 - root - ERROR -   - Required input is missing: images
2024-09-28 12:18:24,235 - root - ERROR - Output will be ignored
2024-09-28 12:18:24,309 - root - WARNING - WARNING: '519'
2024-09-28 12:18:24,706 - root - ERROR - !!! Exception during processing !!! No module named 'florence2_base_ft'
2024-09-28 12:18:24,706 - root - ERROR - Traceback (most recent call last):
  File "F:\ComfyUI-aki-v1.4\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\ComfyUI-aki-v1.4\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\ComfyUI-aki-v1.4\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI-aki-v1.4\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Miaoshouai-Tagger\nodes.py", line 138, in start_tag
    from florence2_base_ft.modeling_florence2 import Florence2ForConditionalGeneration
ModuleNotFoundError: No module named 'florence2_base_ft'

2024-09-28 12:18:24,707 - root - INFO - Prompt executed in 0.47 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by miaoshouai** [comment]
Try redownload the model. Node just updated and need the latest model structure

**Comment by LinYSan** [comment]
> 尝试重新下载模型。节点刚刚更新，需要最新的模型结构
 
您好，已经通过百度网盘和自动下载两种方式重新下了模型，并且删除重装了节点包，还是显示No module named 'florence2_base_ft'

**Comment by miaoshouai** [comment]
models\LLM\Florence-2-base-PromptGen-v1.5的文件夹下面有florence2_base_ft这个文件夹吗？

**Comment by LinYSan** [comment]
有的,内有4个.py文件
![image](https://github.com/user-attachments/assets/98c6dd4f-a91a-40ce-ba88-44e15ab05ac8)

**Comment by WainWong** [comment]
same here

**Comment by LinYSan** [comment]
> models\LLM\Florence-2-base-PromptGen-v1.5的文件夹下面有florence2_base_ft这个文件夹吗？

是的,有这个文件夹
![image](https://github.com/user-attachments/assets/df4ddd83-05b7-443c-894b-add9350cf068)

**Comment by vigee88** [comment]
我也碰到同样的问题，原因是在节点的模型那里选择的 large，如果是选择base模型，就不会有错误提示，可以正常运行（其实我两个模型都已经下载了最新版本）。奇怪的是如果第一次选择base模型推理一次，再选择large模型推理的话，就不会再有错误提示了。如果第一次运行选择large就会有错误提示无法运行。

**Comment by chaaobhu126** [comment]
> 我也碰到同样的问题，原因是在节点的模型那里选择的 large，如果是选择base模型，就不会有错误提示，可以正常运行（其实我两个模型都已经下载了最新版本）。奇怪的是如果第一次选择base模型推理一次，再选择large模型推理的话，就不会再有错误提示了。如果第一次运行选择large就会有错误提示无法运行。

我也是遇到同样的问题，有时新建工作流必须得把LLM下的目录给删除才正常。

**Comment by miaoshouai** [comment]
重新更新一下节点 如果你们已经下载了更新的模型的话，把large模型里面的florence-2-large文件夹更名为florence2_large

**Comment by hansh2020** [comment]
large模型里面有2个florence2_large，需要把另一个删掉吗？否则重命名不了
![Snipaste_2024-10-01_10-30-00](https://github.com/user-attachments/assets/bc1ef240-d1ee-438c-a352-ca009f643c19)



> 重新更新一下节点 如果你们已经下载了更新的模型的话，把large模型里面的florence-2-large文件夹更名为florence2_large

**Comment by miaoshouai** [comment]
refer to this issue for the fix solusion: https://github.com/miaoshouai/ComfyUI-Miaoshouai-Tagger/issues/23#issuecomment-2401340644
