### ISSUE TITLE
no flash_attn import to remove florence2languageforconditionalgeneration has generative capabilities, as prepare_inputs_for_generation is explicitly overwritten. however, it doesn't directly inherit from generationmixin.

### ISSUE THREAD

**Issue by aiise117** [miaoshouai/ComfyUI-Miaoshouai-Tagger#32]
Hello! May I ask why this prompt message appears when loading the model for the first time. How should I set the shutdown prompt? Before, everything went smoothly and the speed of running this node was very fast. However, since I updated pytocr2.5cuida12.4, it takes a long time to load for the first time and there will be corresponding background prompts!

no flash_attn import to remove florence2languageforconditionalgeneration has generative capabilities, as `prepare_inputs_for_generation` is explicitly overwritten. however, it doesn't directly inherit from `generationmixin`. from 👉v4.50👈 onwards, `pretrainedmodel` will not inherit from `generationmixin`, and this model will lose the ability to call `generate` and other related functions. - if you're using `trust_remote_code=true`, you can get rid of this warning by loading the model with an auto class. see https://huggingface.co/docs/transformers/en/model_doc/auto#auto-classes - if you are the owner of the model architecture code, please modify your model class such that it inherits from `generationmixin` (after `pretrainedmodel`, otherwise you'll get an exception). - if you are not the owner of the model architecture class, please contact the model code owner to update it. </s><s>a young woman, positioned directly in front of the camera, with her upper body facing the viewer, she has short, dark brown hair and brown eyes that are looking directly at the viewer with a warm smile on her face, her eyes are a deep brown color, and she is wearing a black sheer top, in the background, there is a cluttered desk with a computer and books, adding to the office setting, the woman's position is slightly off-center, creating a sense of intimacy and closeness, drawing the viewer's attention to her features</s> offloading model...

**Comment by Metal-dude** [comment]
Hi, I had the same problems. After searching on the internet, in the file nodes.py, I replaced attention = 'sdpa' by attention = 'eager' , and the node is functional again.

**Comment by aiise117** [comment]
Thank you~my brother! Indeed, the delay issue has been perfectly resolved. Now it's back to normal processing speed. Thank you very much for your enthusiastic help

**Comment by Quesoquesoqueso0** [comment]
it works for me too thx!


I changed this:

----------------------------------------------------------
            "attention": (
                    [ 'flash_attention_2', 'sdpa', 'eager'],
                    {
                    "default": 'sdpa'
                    }),
----------------------------------------------------------

for this:

----------------------------------------------------------
            "attention": (
                    [ 'flash_attention_2', 'sdpa', 'eager'],
                    {
                    "default": 'eager'
                    }),
----------------------------------------------------------

**Comment by stenfenxx** [comment]
After I modified it, the problem still occurs

**Comment by stenfenxx** [comment]
After I modified it, the problem still occurs，can i know have any other solution?，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，Florence2LanguageForConditionalGeneration has generative capabilities, as `prepare_inputs_for_generation` is explicitly defined. However, it doesn't directly inherit from `GenerationMixin`. From 👉v4.50👈 onwards, `PreTrainedModel` will NOT inherit from `GenerationMixin`, and this model will lose the ability to call `generate` and other related functions.
  - If you're using `trust_remote_code=True`, you can get rid of this warning by loading the model with an auto class. See https://huggingface.co/docs/transformers/en/model_doc/auto#auto-classes
  - If you are the owner of the model architecture code, please modify your model class such that it inherits from `GenerationMixin` (after `PreTrainedModel`, otherwise you'll get an exception).
  - If you are not the owner of the model architecture class, please contact the model code owner to update it.
!!! Exception during processing !!! 'Florence2LanguageForConditionalGeneration' object has no attribute 'generate'
Traceback (most recent call last):
  File "E:\Comfyui\Comfyui\Comfyui\execution.py", line 349, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\Comfyui\Comfyui\Comfyui\execution.py", line 224, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\Comfyui\Comfyui\Comfyui\execution.py", line 196, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\Comfyui\Comfyui\Comfyui\execution.py", line 185, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\Comfyui\Comfyui\Comfyui\custom_nodes\ComfyUI-Miaoshouai-Tagger\nodes.py", line 194, in start_tag
    tags = self.tag_image(image, caption_method, model, processor, device, dtype, max_new_tokens, do_sample, num_beams)
  File "E:\Comfyui\Comfyui\Comfyui\custom_nodes\ComfyUI-Miaoshouai-Tagger\nodes.py", line 96, in tag_image
    generated_ids = model.generate(
  File "E:\Comfyui\Comfyui\Comfyui\.cache\huggingface\modules\transformers_modules\Florence-2-large-PromptGen-v2.0\modeling_florence2.py", line 2796, in generate
    return self.language_model.generate(
  File "E:\Comfyui\Comfyui\Comfyui\python\lib\site-packages\torch\nn\modules\module.py", line 1940, in __getattr__
    raise AttributeError(
AttributeError: 'Florence2LanguageForConditionalGeneration' object has no attribute 'generate'
