### ISSUE TITLE
No module named 'transformers_modules.Florence-2-large-PromptGen-v2'

### ISSUE THREAD

**Issue by Creepybits** [miaoshouai/ComfyUI-Miaoshouai-Tagger#36]
Every time I try to use this I get the error: No module named 'transformers_modules.Florence-2-large-PromptGen-v2'

I've searched all over the place for a solution, but without any luck.

`got prompt
!!! Exception during processing !!! No module named 'transformers_modules.Florence-2-large-PromptGen-v2'
Traceback (most recent call last):
  File "C:\AI Stuff\Comfy\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI Stuff\Comfy\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI Stuff\Comfy\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\AI Stuff\Comfy\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI Stuff\Comfy\ComfyUI\custom_nodes\ComfyUI-Miaoshouai-Tagger\nodes.py", line 140, in start_tag
    model = AutoModelForCausalLM.from_pretrained(model_path, attn_implementation=attention, device_map=device,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI Stuff\Comfy\python_embeded\Lib\site-packages\transformers\models\auto\auto_factory.py", line 521, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI Stuff\Comfy\python_embeded\Lib\site-packages\transformers\models\auto\configuration_auto.py", line 1120, in from_pretrained
    config_class = get_class_from_dynamic_module(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI Stuff\Comfy\python_embeded\Lib\site-packages\transformers\dynamic_module_utils.py", line 500, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI Stuff\Comfy\python_embeded\Lib\site-packages\transformers\dynamic_module_utils.py", line 200, in get_class_in_module
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers_modules.Florence-2-large-PromptGen-v2'`

**Comment by danganbenpa** [comment]
I'm also having this same issue. Just with the V2 versions

**Comment by poweredjj** [comment]
I'm having the same issue.

**Comment by abellos** [comment]
same error with v1.5 or 2

**Comment by danganbenpa** [comment]
For me, this issue turned out to be because transformers was the wrong version. The thing that complicated it was that when I tried to install the right version of transformers there was a node I had installed in ComfyUI that automatically uninstalled transformers and then reinstalled the incorrect version. It took me a while to figure this out but removing the node solved the problem. I can't remember exactly what the node was but i could see where transformers was being updated during ComfyUI starting up and gradually removed nodes until it stopped happening.

**Comment by kirayomato** [comment]
Upgrade the transformers, it works fine for me under 4.48.1
